debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.general.disable_voice"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 72
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.proximity.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 96
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.proximity.toggle"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 77
type = "KEYSYM"

[servers.413874ee-de50-48f2-a8ee-397645f75bf9.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32


[voice]
disabled = false
microphone_disabled = false
activation_threshold = -30.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.proximity]
volume = 1.0
[voice.volumes.source_1f7737f3-ea04-483d-9422-7a20bc72f1b2]
volume = 1.5

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true
jitter_packet_delay = 3
al_playback_buffers = 5

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_LEFT"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "BOTTOM_RIGHT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "ON"
